name: sertit
channels:
  - conda-forge
dependencies:         # everything under this, installed by conda
  - python=3.10
  - pip
  - pip:                # everything under this, installed by pip
      - -r requirements.txt
